name: Gomora CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Copy env file
      run: cp .env.example .env

    - name: Build
      run: make build

    - name: Log in to Gitlab Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}

    - name: Push Docker Image to Gitlab Container Registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: registry.gitlab.com/nuxify/container-registry/devops-training/gomora:latest
